# This configuration file enables a comprehensive set of RuboCop cops for code style checking

# Enable new cops by default
AllCops:
  NewCops: enable

# Include additional cops
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-minitest

# Inherit from the Rails Omakase configuration
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# You can override specific cops if needed, for example:
Style/Documentation:
  Enabled: false

# Add any project-specific overrides or configurations below
